### ISSUE TITLE
Version 1.1 Checklist

### ISSUE THREAD

**Issue by cgmb** [cgmb/KongoniBridge#1]
- [x] Check stress forces are being calculated correctly
- [x] Choose reasonable values for fundamental constants
- [x] Fix background music
- [x] Reset bridge after testing is complete
- [ ] Limit beam length
- [x] Use different colours for beam tension and compression
- [ ] Fix background resizing
- [ ] Improve editing interface
- [ ] Release for OSX
